namespace HR.LeaveManagement.BlazorWebAssyUI.Services.Base
{
    /// <summary>
    /// Extends IClient from ServiceClient code generated by NSwagStudio
    /// </summary>
    public partial interface IClient
    {
        public HttpClient HttpClient { get; }
    }
}
